### ISSUE TITLE
unify: Job list

### ISSUE THREAD

**Issue by linD026** [linD026/ucsan#5]
# stack information

* MacOS/Linux
    * [backtrace()](https://man7.org/linux/man-pages/man3/backtrace.3.html)
* Windows
    * [CaptureStackBackTrace](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/bb204633(v=vs.85)?redirectedfrom=MSDN)  

# task information

* Process class
```cpp
typedef int pid_t;
struct task_struct {
	int pid; /* from OS */
 	int cpuid; /* from OS */
	bool read_write_state; /* read:true, write:false */
	void *address; /* Address of object */
	size_t size; /* size of object, unit is byte */
	/* link to others task_struct for one watchpoint */
};
```
* pid :  https://man7.org/linux/man-pages/man2/getpid.2.html
* CPU id : https://man7.org/linux/man-pages/man3/sched_getcpu.3.html

```cpp
void unify::report(void *ptr, size_t size, int state)
{
    // store and create the task info
    task_struct *task = create_task(ptr, size, state); 
    stack_info *stack_info;
    
    // Add task to task_container, collect the task
    // task_container probably will be array, the set of task
    create_task_container(task_container, task);
	
    stack_info = collect_stack_info();
    
    report_to_system(together(stack_info, task_container));
}
```

**Comment by linD026** [comment]
@celizon @ZitingLi

**Comment by linD026** [comment]
@celizon
Could you please check out the report message of this [function](https://github.com/gcc-mirror/gcc/blob/e8ed26c2ac38ab1f6ed5a627d9089a9243e06a0c/libsanitizer/tsan/tsan_report.cpp#L300) for environment information that we will need in our project?
Like, how do they collect the information of threads, and how do they deal with the stack information?

After that, we can let the people who are responsible for the detect or report part know how to do their job with the information.

**Comment by linD026** [comment]
I create the PR for the basic concept of how the detect and unify subsystems interact.
* https://github.com/linD026/ucsan/pull/10

So your job is to implement the function in the src/unify file.

**Comment by celizon** [comment]
**已完成：task、stack、時間**
 **未完成：行數**

我們建立了Unify.cpp、Unify.h，以及main.cpp三個檔案，其中main.cpp是作為測試用，模擬怎麼調用Unify的函式。編譯後的執行檔暫時命名為example。下圖片example的輸出樣式，之後會再加上一行value change。
![image](https://user-images.githubusercontent.com/51367207/174462001-e04aa19e-65f0-478a-833e-e632fe0015c7.png)


### 以下有**3個問題**需要請教：

**問題1：stack的backtrace顯示問題**
因為打包成一個.exe的關係，stack的backtrace()無法顯示內部經過的函式，只有記憶體位址。
如果在int main()直接調用unify函式，結果如下圖，backtrace()有5行。
![image](https://user-images.githubusercontent.com/51367207/174462029-e95e7d32-b96f-4468-bbec-6e6c3c9ac728.png)
如果在int main()內呼叫void func1()，並在func1()裡才調用unify函式，結果如下圖，backtrace()有6行，等於多了經過func1()的位址。
![image](https://user-images.githubusercontent.com/51367207/174462041-076abba2-a6d5-4c7b-a3b4-0a7c72f09254.png)

**問題2：無法取得出現data race的行數。**
有嘗試過使用__Line__和addr2line獲取行數，但不適用於我們的程式。網路上也查不到如何從外部程式碼取得目標程式碼的行數。

**問題3：出現data race的時間擷取。**
不確定時間是要拿time()還是clock ()，前者是現實的執行時間，後者是程式內部的執行時間。目前是使用clock()。
![image](https://user-images.githubusercontent.com/51367207/174462054-121c4a2e-9728-4c92-b91d-2e1a47fd5d19.png)
![image](https://user-images.githubusercontent.com/51367207/174462057-00898bb3-7d9c-4ffd-9be4-638e923afbf9.png)

**Comment by celizon** [comment]
Unify.h 程式碼：
```
#pragma once
#include <iostream>
#include <string>
#include <vector>
#include <sstream>
#include <utility>
#include <map>
#include <fstream>
#include <time.h>
#include <unistd.h>
#include <sched.h>
#include <stdio.h>
#include <stdlib.h>
#include <execinfo.h>
using namespace std;

typedef class Task {
public:
	pid_t pid; /* from OS */
	int cpuid; /* from OS */
	bool read_write_state; /* read:true(1), write:false(0) */
	unsigned long long* address; /* Address of object */
	size_t size; /* size of object, unit is byte */
	clock_t current_time;
	vector<string> stack;
	Task(){};
	Task(unsigned long long* ptr, size_t _size, int state) {
		this->pid = getpid();
		this->cpuid = sched_getcpu();
		this->read_write_state = state;
		this->address = ptr;
		this->size = _size;
		this->current_time = clock();
	};
}task;

class Unify {
private:
	int line_number;
	size_t time;
public:
	map<pair<unsigned long long*, size_t>, vector<task> > task_container;
	void report_set_info(unsigned long long* ptr, size_t _size, int state);
	vector<string> collect_stack_info();
	void report_to_detect();
	void write_file();
};

```

**Comment by celizon** [comment]
Unify.cpp 程式碼：
```
#include "Unify.h"

void Unify::report_set_info(unsigned long long* ptr, size_t _size, int state) {

    pair<unsigned long long*, size_t> v(ptr, _size);
    task t(ptr, _size, state);
    t.stack = collect_stack_info();
    task_container[v].push_back(t);
}

vector<string> Unify::collect_stack_info() {
    void* buffer[64];
    char** symbols;

    int num = backtrace(buffer, 64);

    symbols = backtrace_symbols(buffer, num);
    if (symbols == NULL) {
        perror("backtrace_symbols");
        exit(EXIT_FAILURE);
    }

    vector<string> temp;
    for (int i = 0; i < num; i++) {
        temp.push_back(symbols[i]);
    }

    free(symbols);
    return temp;
}

void Unify::report_to_detect() {

}

void Unify::write_file() {
    ofstream file;
    file.open("conclusion.txt");
    if (!file.is_open()){
	cout << "File cannot be open.";
    }
    else {
        for (map<pair<unsigned long long*, size_t>, vector<task> >::iterator it = task_container.begin(); it != task_container.end(); it++) {
            file << "address " << it->first.first << endl;
            file << "size " << it->first.second << endl;
            for (int i = 0; i < it->second.size(); i++) {
                file << "pid " << it->second[i].pid << endl;
                file << "cpuid " << it->second[i].cpuid << endl;
                file << "state " << it->second[i].read_write_state << endl;
		file << "time " << it->second[i].current_time << endl;
                for (int j = 0; j < it->second[i].stack.size(); j++) {
                    file << it->second[i].stack[j] << endl;
                }
            }
        }
	file.close();
    }
}
```

**Comment by linD026** [comment]
For question 1, after using the backtrace() function, you should use the backtrace_symbols() function to translate the address.

Here is the manual page said:
> Given the set of addresses returned by backtrace() in buffer,
> backtrace_symbols() translates the addresses into an array of
> strings that describe the addresses symbolically.

Other, it is totally fine.

**Comment by celizon** [comment]
有使用backtrace_symbols()，不知道是哪裡少做，才會不傳內部function calls。
之前將backtrace直接放在main裡，是會顯示的，有參考[backtrace()](https://man7.org/linux/man-pages/man3/backtrace.3.html)範例的做法。
三個檔案(main.cpp、Unify.h、Unify.h)一起編譯後，就無法顯示。

**Comment by linD026** [comment]
OK, I will fix it.

And from your code, I don't see any that let us really need to use C++.
The only feature you use is OOP.
But for your code, the class you use is [POD class type](https://en.cppreference.com/w/cpp/language/classes#POD_class).
It seems like you are writing the C style of C++.
So I would rewrite the code to make the integration easier.

**Comment by linD026** [comment]
The PR is here:
* https://github.com/linD026/ucsan/pull/17

Please check this out.
